version: '3.4'

services:
  homecloud.gateway:
    image: davidstahl97/homecloud
    build:
      context: .
      dockerfile: HomeCloud.Gateway/Dockerfile

  homecloud.map.webapi:
    image: davidstahl97/homecloud
    build:
      context: .
      dockerfile: HomeCloud.Map/HomeCloud.Map.WebAPI/HomeCloud.Map.Presentation/Dockerfile

