version: '3.4'

services:
  homeapp.gateway:
    image: ${DOCKER_REGISTRY-}homeappgateway
    build:
      context: .
      dockerfile: HomeApp.Gateway/Dockerfile

  homeapp.map.webapi:
    image: ${DOCKER_REGISTRY-}homeappmapwebapi
    build:
      context: .
      dockerfile: HomeApp.Map/HomeApp.Map.WebAPI/Server/Dockerfile

