version: '3.4'

services:
  homecloud-maps-server:
    container_name: homecloud-maps-server
    image: davidstahl97/homecloud-maps-server
    build:
      context: .
      dockerfile: ./src/backend/HomeCloud.Maps.Server/Dockerfile
    ports:
      - "80:5001"
      - "443:5000"
    environment:
      - ASPNETCORE_URLS=https://+:5000;http://+:5001
    volumes:
      - ~/.aspnet/https:/https:ro
