version: '3.4'

services:
  homecloud-maps-server:
    container_name: homecloud-maps-server
    image: davidstahl97/homecloud-maps-server
    build:
      context: .
      dockerfile: ./src/backend/HomeCloud.Maps.Server/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:5000;http://+:5001      
    volumes:
      - ~/.aspnet/https:/https:ro
    external_links:
      - mongo
    env_file:
      - homecloud-maps-server.env
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - mongo.env
    volumes:
      - ./mongo-volumne:/data/db   