version: '3.4'

services:
  homecloud-maps-server:
    container_name: homecloud-maps-server
    image: davidstahl97/homecloud-maps-server
    build:
      context: .
      dockerfile: ./src/backend/HomeCloud.Maps.Server/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:5000;http://+:5001
      - MongoDb__ConnectionString=mongodb://mongo:27017
    volumes:
      - ~/.aspnet/https:/https:ro
    external_links:
      - mongo 
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'