version: '3.4'

services:
  homeapp.gateway:
    image: ${DOCKER_REGISTRY-}homeappgateway
    build:
      context: .
      dockerfile: HomeApp.Gateway/Dockerfile

  homeapp.server:
    image: ${DOCKER_REGISTRY-}homeappserver
    build:
      context: .
      dockerfile: HomeApp/Server/Presentation/Server/Dockerfile

