version: '3.4'

services:
  homecloud-maps-server:
    container_name: homecloud-maps-server
    image: davidstahl97/homecloud-maps-server
    build:
      context: .
      dockerfile: ./src/backend/HomeCloud.Maps.Server/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:5000;http://+:5001      
      - MongoDb__ConnectionString=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
    volumes:
      - ~/.aspnet/https:/https:ro
    external_links:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./mongo-volumne:/data/db   