version: '3.4'

services:
  homecloud.gateway:
    image: davidstahl97/homecloud-gateway
    build:
      context: .
      dockerfile: HomeCloud.Gateway/Dockerfile
    ports:
        - "80:5001"
        - "443:5000"
    environment:
        - ASPNETCORE_URLS=http://+:5001;https://+:5000
        - ASPNETCORE_Kestrel__Certificates__Default__Password=test123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/homecloud/homecloud-david.private_key.pfx

  homecloud.map.webapi:
    image: davidstahl97/homecloud-map-webapi
    build:
      context: .
      dockerfile: HomeCloud.Map/HomeCloud.Map.WebAPI/HomeCloud.Map.Presentation/Dockerfile
    ports:
        - "5010:5010"
    environment:
        - ASPNETCORE_URLS=http://+:5010

