version: '3.4'

services:
  homecloud.gateway:
    container_name: homecloud.gateway
    ports:
      - "80:5001"
      - "443:5000"
    environment:
      - ASPNETCORE_URLS=https://+:5000;http://+:5001
    volumes:
      - ~/.aspnet/https:/https:ro

  homecloud.map.webapi:
    container_name: homecloud.map.webapi
    ports:
        - "5010:5010"
    environment:
        - ASPNETCORE_URLS=http://+:5010
        - ASPNETCORE_ENVIRONMENT=Development
        
  homecloud.users.service:
    container_name: homecloud.users.service
    ports:
        - "64676:64676"
    environment:
        - ASPNETCORE_URLS=http://+:64676
        - ConnectionStrings__SqlConnection=Server=usersdb;Database=UsersDb;User=sa;Password=BigPassw0rd
    depends_on:
        - usersdb
        
  usersdb:
    container_name: homecloud.users.db
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: 'usersdb'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD="BigPassw0rd"      
    volumes:
      - ./data/mssql:/var/opt/mssql/data
    ports:
      - '1433:1433'  
