version: '3.4'

services:
  homecloud.gateway:
    container_name: homecloud.gateway
    image: davidstahl97/homecloud-gateway
    build:
      context: .
      dockerfile: HomeCloud.Gateway/Dockerfile
    ports:
        - "80:5001"
        - "443:5000"
    environment:
        - ASPNETCORE_URLS=http://+:5001;https://+:5000
        - ASPNETCORE_Kestrel__Certificates__Default__Password=test123
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/homecloud-david.private_key.pfx
        - ASPNETCORE_ENVIRONMENT=Production
    volumes:
        - ~/.aspnet/https:/https:ro

  homecloud.map.webapi:
    container_name: homecloud.map.webapi
    image: davidstahl97/homecloud-map-webapi
    build:
      context: .
      dockerfile: HomeCloud.Map/HomeCloud.Map.WebAPI/HomeCloud.Map.Presentation/Dockerfile
    ports:
        - "5010:5010"
    environment:
        - ASPNETCORE_URLS=http://+:5010
        - ASPNETCORE_ENVIRONMENT=Production
        
  homecloud.users.service:
    container_name: homecloud.users.service
    image: davidstahl97/homecloud-users-service
    build:
        context: .
        dockerfile: HomeCloud.Users/HomeCloud.Users.Service/Dockerfile
    ports:
        - "64676:64676"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production

