name: .NET Core

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies HomeApp.Gateway
      run: dotnet restore HomeApp.Gateway
    - name: Build HomeApp.Gateway
      run: dotnet build HomeApp.Gateway --configuration Release --no-restore
    
    - name: Install dependencies HomeApp.Map/HomeApp.Map.WebAPI/Server
      run: dotnet restore HomeApp.Map/HomeApp.Map.WebAPI/Server
    - name: Build
      run: dotnet build HomeApp.Map/HomeApp.Map.WebAPI/Server --configuration Release --no-restore
