name: .NET Core

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies HomeCloud.Gateway
      run: dotnet restore HomeCloud.Gateway
    - name: Build HomeCloud.Gateway
      run: dotnet build HomeCloud.Gateway --configuration Release --no-restore
    
    - name: Install dependencies HomeCloud.Map/HomeCloud.Map.WebAPI/HomeCloud.Map.Presentation
      run: dotnet restore HomeCloud.Map/HomeCloud.Map.WebAPI/HomeCloud.Map.Presentation
    - name: Build HomeCloud.Map/HomeCloud.Map.WebAPI/HomeCloud.Map.Presentation
      run: dotnet build HomeCloud.Map/HomeCloud.Map.WebAPI/HomeCloud.Map.Presentation --configuration Release --no-restore
