name: .NET Core

on:
  push:
    branches: [ release ]

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Docker Compose
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
      - name: Publish Docker images
        run: docker-compose push
      - name: Logout
        run: docker logout  
        
  publish:
    name: Publish - Server
    runs-on: ubuntu-latest
    needs: [ docker ]
    steps:
      - name: executing remote docker pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /
            cd homecloud
            curl --remote-name https://raw.githubusercontent.com/DavidStahl97/HomeCloud/master/docker-compose.yml
            curl --remote-name https://raw.githubusercontent.com/DavidStahl97/HomeCloud/master/docker-compose.prod.yml
            
            docker-compose down
            docker pull davidstahl97/homecloud-maps-server
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
