name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - release

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore HomeCloud.sln
    - name: Build
      run: dotnet build HomeCloud.sln --no-restore
    - name: Test
      run: dotnet test HomeCloud.sln /p:CollectCoverage=true --no-build --verbosity normal
